services:
  - type: web
    name: ideal-worldcup
    runtime: python
    rootDir: ideal-worldcup
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
